### ISSUE TITLE
圈x问题

### ISSUE THREAD

**Issue by manhuaxian** [im-yunzetian/chromego#1]
大佬，你设置的这个订阅，怎么才能在圈x里使用呀？

**Comment by im-yunzetian** [comment]
订阅里的有些协议在圈x是没有的，可以自己手动添加圈x支持的协议

**Comment by im-yunzetian** [comment]
> 大佬，你设置的这个订阅，怎么才能在圈x里使用呀？

订阅里的有些协议在圈x是没有的，可以自己手动添加圈x支持的协议

**Comment by manhuaxian** [comment]
我好像懂了，从Chromego中提取josn里的链接，做成和你这个一样的raw，用这个raw订阅对吧发自我的 iPhone在 2024年1月21日，22:16，Yunzetian ***@***.***> 写道：﻿
订阅里的有些协议在圈x是没有的，可以自己手动添加圈x支持的协议
